# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
# ✅ Install .NET 9.0
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '9.0.x'
    includePreviewVersions: true

# ✅ Restore and Build
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build Project'
